export default class Events {

	static listEventTypes = [
		{id:  0, value: 'create',     name: 'Create',      getFullName: () => 'Create'},
		{id:  1, value: 'destroy',    name: 'Destroy',     getFullName: () => 'Destroy'},
		{id:  3, value: 'step',       name: 'Step',        getFullName: (subtype) => Events.listStepSubtypes[subtype]},
		{id:  2, value: 'alarm',      name: 'Alarm',       getFullName: (subtype) => 'Alarm '+subtype},
		{id:  5, value: 'keyboard',   name: 'Keyboard',    getFullName: (subtype) => 'Keyboard '+subtype},
		{id:  6, value: 'mouse',      name: 'Mouse',       getFullName: (subtype) => Events.listMouseSubtypes[subtype]},
		{id:  4, value: 'collision',  name: 'Collision',   getFullName: (subtype, project) => 'Collision with '+ (project.resources.ProjectObject.find(x => x.id == subtype).name)},
		{id:  7, value: 'other',      name: 'Other',       getFullName: (subtype) => Events.listOtherSubtypes[subtype]},
		{id:  8, value: 'draw',       name: 'Draw',        getFullName: () => 'Draw'},
		{id:  9, value: 'keypress',   name: 'Key press',   getFullName: (subtype) => 'Key press'+subtype},
		{id: 10, value: 'keyrelease', name: 'Key release', getFullName: (subtype) => 'Key release'+subtype},
	];

	static listStepSubtypes = {
		'normal': 'Step',
		'begin': 'Begin step',
		'end': 'End step',
	};

	static listMouseSubtypes = {
		0: 'Left Button',
		1: 'Right Button',
		2: 'Middle Button',
		3: 'No Button',
		4: 'Left Press',
		5: 'Right Press',
		6: 'Middle Press',
		7: 'Left Release',
		8: 'Right Release',
		9: 'Middle Release',
		10: 'Mouse Enter',
		11: 'Mouse Leave',
		12: 'Global Press',
		13: 'Global Release',
		16: 'Joystick1 Left',
		17: 'Joystick1 Right',
		18: 'Joystick1 Up',
		19: 'Joystick1 Down',
		21: 'Joystick1 Button1',
		22: 'Joystick1 Button2',
		23: 'Joystick1 Button3',
		24: 'Joystick1 Button4',
		25: 'Joystick1 Button5',
		26: 'Joystick1 Button6',
		27: 'Joystick1 Button7',
		28: 'Joystick1 Button8',
		31: 'Joystick2 Left',
		32: 'Joystick2 Right',
		33: 'Joystick2 Up',
		34: 'Joystick2 Down',
		36: 'Joystick2 Button1',
		37: 'Joystick2 Button2',
		38: 'Joystick2 Button3',
		39: 'Joystick2 Button4',
		40: 'Joystick2 Button5',
		41: 'Joystick2 Button6',
		42: 'Joystick2 Button7',
		43: 'Joystick2 Button8',
		50: 'Global Left Button',
		51: 'Global Right Button',
		52: 'Global Middle Button',
		53: 'Global Left Press',
		54: 'Global Right Press',
		55: 'Global Middle Press',
		56: 'Global Left Release',
		57: 'Global Right Release',
		58: 'Global Middle Release',
		60: 'Mouse Wheel Up',
		61: 'Mouse Wheel Down',
	};

	static listOtherSubtypes = {
		0: 'Outside',
		1: 'Boundary',
		2: 'Game start',
		3: 'Game end',
		4: 'Room start',
		5: 'Room end',
		6: 'No more lives',
		7: 'Animation end',
		8: 'End of path',
		9: 'No more health',
		10: 'User 0',
		11: 'User 1',
		12: 'User 2',
		13: 'User 3',
		14: 'User 4',
		15: 'User 5',
		16: 'User 6',
		17: 'User 7',
		18: 'User 8',
		19: 'User 9',
		20: 'User 10',
		21: 'User 11',
		22: 'User 12',
		23: 'User 13',
		24: 'User 14',
		25: 'User 15',
		30: 'Close button',
	}

	static getEventName(event, project) {
		return Events.listEventTypes.find(x => x.value == event.type).getFullName(event.subtype, project);
	}
}